version: '3.8'
services:
  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=GMT

  server:
    build: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit_db
      - TZ=GMT

  postgres:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=GMT